#!/bin/bash

if [ -d "$1" ]; then
	>ex2.txt
	cd $1 2> errors
	k=0
	array=( $(find . -type f -depth ) ) 
	for i in ${array[@]}
	do
		stat -c "%A %s %n" $i| tee -a ex2.txt
		((k++)) 
	done
	echo Listed $k files| tee -a ex2.txt
else
	echo "Directory "$1" not founded">&2
fi	
  
	
	



