#!/bin/bash
if [ "$#" -lt 3 ]; then
	echo "Недостаточно параметров." >&2
	echo "Par1 - имя файла для вывода результата."
	echo "Par2 - директория поика."
	echo "Par3 - расширение."
elif [ ! -d "$2" ]; then
	echo "Директория "$2" не найдена." >&2
else
	files=$(find "$2" -iname "*.$3" | sort --output="$1")
fi
